[package]
name = "Task_PassVault"
version = "0.1.0"
edition = "2021"

[dependencies]
# JSON-related dependencies (commented out)
# serde = { version = "1.0", features = ["derive"] }
# serde_json = "1.0"

# SQLite dependency
rusqlite = { version = "0.30.0", features = ["bundled"] }
